services:
  - type: web
    name: kvcet-erp-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    rootDir: server
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
